name: Publish Python distributions to PyPI

on:
  release:
    types: [published]

env:
  WECOM_WEBHOOK_URL: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${{ secrets.WECOM_WEBHOOK_KEY }}

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Notify success
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          const webhookUrl = "${{ env.WECOM_WEBHOOK_URL }}";
          const messageContent = "${{ github.repository }}" + "发布成功！";
          const message = {
            msgtype: "text",
            text: {
              content: messageContent
            }
          };
          await github.request("POST " + webhookUrl, {
            data: message,
            headers: {
              "Content-Type": "application/json"
            }
          });
    - name: Notify failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const webhookUrl = "${{ env.WECOM_WEBHOOK_URL }}";
          const messageContent = "${{ github.repository }}" + "发布失败！";
          const message = {
            msgtype: "text",
            text: {
              content: messageContent
            }
          };
          await github.request("POST " + webhookUrl, {
            data: message,
            headers: {
              "Content-Type": "application/json"
            }
          });
